Chore: Rm dup entry from policy/common INFO.yaml
The committer 'liamfallon' was listed twice in the committers section:
1. Via YAML anchor reference (<<: *onap_releng_ptl)
2. As an explicit entry

This duplicate caused the LDAP matching script to fail with:
ValueError: list.remove(x): x not in list

Change-Id: I9f7c0045232f4a5a2240e76388ecf03760096d8d
Signed-off-by: Anil Belur <abelur@linuxfoundation.org>